disabled_rules: # rule identifiers to exclude from running
 - colon
 - comma

excluded:
- GitClient/Generated


  
line_length:
    warning: 180
    error: 220
    ignores_comments: true
    
identifier_name:
  min_length: 1
  max_length: 30
 
type_name:
  max_length:
    warning: 50
    
nesting:
    type_level: 3
  
force_try: warning
force_cast: warning

reporter: "xcode"


